[proxy]
# 代理设置，对 Telegram Bot API 无效
# 如需配置 Telegram 代理，请设置环境变量 HTTP_PROXY
# 参考 https://github.com/go-telegram-bot-api/telegram-bot-api/issues/288
Enabled=false
Addr=""

[sources]
[sources.Pixiv]
# Pixiv 源
Enabled=false
RssURL=""
RefreshTime=60 # 抓取到新收藏后，间隔多少分钟抓取下一次
Interval=20 # 无新收藏时，再间隔多少分钟抓取一次

[storages]
[storages.TelegramChannel]
# Telegram 频道存储
Enabled=false
UserName="" #记得带上@
ChatID=0

[middlewares]
[middlewares.TelegramBot]
# Telegram 机器人中间件
Enabled=false
Token=""