[proxy]
Enabled=false
Addr=""

[sources]
[sources.Pixiv]
Enabled=false
RssURL=""
RefreshTime=120

[storages]
[storages.TelegramChannel]
Enabled=false
UserName=""

[middlewares]
[middlewares.TelegramBot]
Enabled=false
Token=""