name: Build and release

on:
  push:
    tags:
      - "*"
permissions:
  contents: write

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: changelog
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          chmod +x ./build.sh
      - name: Build
        run: |
          bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
